version: "3"
services:
  api:
    image: yusukeiwaki/cloud-pine-admin
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: python3 main.py
    environment:
      - PORT=5042
      - C9_WORKSPACE_DOCKER_COMPOSE_URL
    ports:
      - 5042
    deploy:
      placement:
        constraints:
          - 'node.role==manager'

networks:
  default:
    external:
      name: cloud-pine-admin
